# Main background, empty for terminal default, need to be empty if you want transparent background
#theme[main_bg]="#15110f"

theme[main_bg]=""

# Main text color
theme[main_fg]="#cdc3b4"

# Title color for boxes
theme[title]="#cfa47d"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#73888a"

# Background color of selected item in processes box
theme[selected_bg]="#4d4239"

# Foreground color of selected item in processes box
theme[selected_fg]="#cdc3b4"

# Color of inactive/disabled text
theme[inactive_fg]="#4d4239"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#cfa47d"

# Box outline and divider line color
theme[cpu_box]="#6f7a52"
theme[mem_box]="#6f7a52"
theme[net_box]="#6f7a52"
theme[proc_box]="#6f7a52"
theme[div_line]="#4d4239"

# Gradient for all meters and graphs
theme[temp_start]="#73888a"
theme[temp_mid]="#5b6e7a"
theme[temp_end]="#6f7a52"


theme[cpu_start]="#73888a"
theme[cpu_mid]="#5b6e7a"
theme[cpu_end]="#6f7a52"


theme[free_start]="#5b6e7a"
theme[free_mid]="#b08a4f"
theme[free_end]="#b08a4f"


theme[cached_start]="#b08a4f"
theme[cached_mid]="#b08a4f"
theme[cached_end]="#b08a4f"


theme[available_start]="#73888a"
theme[available_mid]="#73888a"
theme[available_end]="#73888a"


theme[used_start]="#6f7a52"
theme[used_mid]="#6f7a52"
theme[used_end]="#6f7a52"


theme[download_start]="#b08a4f"
theme[download_mid]="#73888a"
theme[download_end]="#5b6e7a"


theme[upload_start]="#b08a4f"
theme[upload_mid]="#73888a"
theme[upload_end]="#5b6e7a"
