$color = rgba(21, 17, 15, 1)
$inner_color = rgba(21, 17, 15, 0.66)
$outer_color = rgba(192, 57, 43, 1)
$font_color = rgba(205, 195, 180, 1)
$placeholder_color = rgba(205, 195, 180, 0.7)
$check_color = rgba(158, 27, 27, 1)
