background            #15110f
foreground            #cdc3b4

# black
color0  #15110f
color8  #4d4239

# red
color1  #9e1b1b
color9  #c0392b

# green
color2  #6f7a52
color10 #869171

# yellow
color3  #b08a4f
color11 #c9a86a

# blue
color4  #5b6e7a
color12 #7e909b

# magenta
color5  #7d4a44
color13 #a06a60

#cyan
color6  #73888a
color14 #94a6a6

#white
color7  #cdc3b4
color15 #cdc3b4

# Transparency
background_opacity 0.8